### ISSUE TITLE
Improve default algo / metrics / opener

### ISSUE THREAD

**Issue by samlesu** [SubstraFoundation/substra-tests#14]
The current implementation of the algo, the metrics and the opener are returning hard coded values that don't depend on the input values.

It doesn't allow to check that the output models / predictions and score are computed as expected.

It will be better if the implementation of these assets make sense from a Machine Learning point of view.

Tasks:
- [ ] Define structure to use (must be simple to implement and simple to use, i.e. expected results should be easy to compute on the side)
- [ ] Implement it
- [ ] Improve existing tests to ensure the task outputs are correct

**Comment by jmorel** [comment]
I think that from the test framework, the only output we can see is the potential score. Which means in order to add checks on the execution, we'd have to add testtuples pretty much everywhere. This would make tests slower to run. Is this still a thing we want to do?

**Comment by samlesu** [comment]
Yes, indeed currently the only output is the score.

In my point of view if the algo is validated in at least one test it would be enough.
If the model / data samples have not a valid format the train/test tuple will (should) not be able to run successfully.

**Comment by Kelvin-M** [comment]
Is it still relevant @samlesu @jmorel  ?

**Comment by samlesu** [comment]
In my opinion we can close it, this ticket is too old :)
