### ISSUE TITLE
xargs " --no-run-if-empty " does not exist on mac os

### ISSUE THREAD

**Issue by Kelvin-M** [SubstraFoundation/substra-tests#161]
The PR https://github.com/SubstraFoundation/substra-tests/pull/160 uses an option that is not available in the BSD implementation of xargs in MacOs

**Comment by Kelvin-M** [comment]
Xargs no-run-if-empty mac

Ignore empty results for xargs in Mac OS X, Indeed, the BSD implementation of xargs doesn't have the -r flag ( --no-run-if-​empty ). The GNU version in Linux has it. Here's one way to work  This is a behaviour of GNU xargs which can be supressed by using -r, --no-run-if-empty. The *BSD variant of xargs has this behavoir on default, so -r is not needed. Since FreeBSD 7.1 (released in january 2009) an -r argument is accepted (witch does nothing) for compatiblity reasons.

**Comment by AurelienGasser** [comment]
@Kelvin-M Can you confirm that on Mac this comment has no output?

```
echo -n "" | xargs -r echo toto
```

**Comment by Kelvin-M** [comment]
Nope, as written on my previous comment , `-r` and `--no-run-if-empty` do not exist on MacOs `xargs` implementation.
It's the default behavior

```shell
echo -n "" | xargs echo toto
```

has no output :)

**Comment by AurelienGasser** [comment]
Ah my mistake, thanks.
