### ISSUE TITLE
Tests: mark/skip tests that cannot run without shared folder

### ISSUE THREAD

**Issue by samlesu** [SubstraFoundation/substra-tests#35]
Some tests required a shared folder to add data samples, we should mark or skip them to be able to run the tests with an environment located in gcp for instance.

**Comment by jmorel** [comment]
I think this has been fixed in #57 with the addition of `HAS_SHARED_PATH`: https://github.com/SubstraFoundation/substra-tests/pull/57/files#diff-0e1374e4f64248468c2fa78d8d02c5baR47
Could you check it and close the issue if it's indeed done?

**Comment by samlesu** [comment]
Yes, indeed. Thanks!
