### ISSUE TITLE
Split session object into client and state

### ISSUE THREAD

**Issue by jmorel** [SubstraFoundation/substra-tests#76]
Currently each session has its own state which contains the assets created (and owned) by the session during the current test run. 

The objective of the session is to contain all assets necessary for the execution of a test. For example, the fixture `global_execution_env` returns sessions which contain all necessary assets to run `test_aggregatetuple`

In order to better reflect this, we'd like to separate the session object into 2 independent object:
* `Client` (replaces `Session`) is a wrapper around `substra.Client` to handle serialization
* `State` is an independent object with private properties (`state._dataset`) and public methods to access assets owned by a given node (`state.get_dataset(node_id)`)

Fixtures such as `global_execution_env` would then not return a factory and a network but instead a factory and a state containing all assets created by the fixture.

Individual tests such as `test_aggregatetuple` would therefore need to get as args the fixture `global_execution_env` and a `clients` fixture (or multiple individual fixtures `client_1`, `client_2` etc.)

This will lead to a pretty big renaming throughout the tests (no more sessions, only clients and states instead)

**Comment by jmorel** [comment]
Thanks a lot @maeldebon for this very nice change! 

I see now a few follow up tasks:
* rename `Session` in `Client`
* remove `test_data_samples` and `test_data_samples` from `_Assets` since they are not used anywhere
* add a `filter_by(node_id)` method to the Assets object that accepts as argument a string (or even better, a string or a Client object) and returns a new Assets object which contains all datasets/objectives whose owner is the given node_id
* update all tests to use this new filter_by method instead of list comprehensions
* make _Assets a standard class (it does not need to depend on pydantic) and store actual assets in private properties (i.e. `_objectives`, `_datasets`) and have public getters (using `@property`) for them. This way the object will be effectively read-only.

**Comment by maeldebon** [comment]
I'll do it @jmorel, thanks! 😄 
I was just checking for the following point:
> remove test_data_samples and test_data_samples from _Assets since they are not used anywhere

It looks like this is still used in some tests 🙁

**Comment by jmorel** [comment]
Could you tell me where? I made a search for `test_data_samples` and `train_data_samples` but couldn't find any use of the variables in tests, only in `global_execution_env` where they are written into but never read from.

**Comment by maeldebon** [comment]
> Could you tell me where? I made a search for `test_data_samples` and `train_data_samples` but couldn't find any use of the variables in tests, only in `global_execution_env` where they are written into but never read from.

My bad, this is indeed only used in `global_execution_env`. We need a `test_data_sample` to create an objective, which is later used in the tests. If I try to remove it from the objective creation, I get this exception:
```sh
none is not an allowed value
```

**Comment by jmorel** [comment]
I'm not suggesting we remove the creation of any test data sample, but rather that we don't store it in the _Assets catalog anymore.

**Comment by samlesu** [comment]
Has been done by @maeldebon.
