### ISSUE TITLE
SUBSTRAT_* global variables

### ISSUE THREAD

**Issue by GuillaumeCisco** [SubstraFoundation/substra-tests#9]
This project uses SUBSTRA`T` as a prefix for global variables (note the extra `T`).
All others projects in the substra ecosystem use a `SUBSTRA` prefix.

For coherence and avoiding misunderstanding, this project should use `SUBSTRA_*` prefix for its global variables.

**Comment by samlesu** [comment]
The `SUBSTRAT` prefix was referring to the name of the tests package name (`substra`). It has been renamed to `substratests` recently. 

We could rename `SUBSTRAT` to `SUBSTRA` or `SUBSTRA_TESTS` (to avoid conflicts?). Both solutions look good to me.
